function ReportGenerator({ classData }) {
  try {
    const getWeekRange = (date) => {
      const startOfWeek = new Date(date);
      const day = startOfWeek.getDay();
      const diff = startOfWeek.getDate() - day + (day === 0 ? -6 : 1);
      startOfWeek.setDate(diff);
      
      const endOfWeek = new Date(startOfWeek);
      endOfWeek.setDate(startOfWeek.getDate() + 6);
      
      return {
        start: startOfWeek.toISOString().split('T')[0],
        end: endOfWeek.toISOString().split('T')[0]
      };
    };

    const [reportType, setReportType] = React.useState('summary');
    const [dateRange, setDateRange] = React.useState('30');
    const [selectedDate, setSelectedDate] = React.useState(new Date().toISOString().split('T')[0]);
    const [selectedMonth, setSelectedMonth] = React.useState(new Date().toISOString().slice(0, 7));
    const [selectedWeek, setSelectedWeek] = React.useState(getWeekRange(new Date()));
    const [showScheduleForm, setShowScheduleForm] = React.useState(false);
    const [isPrintMode, setIsPrintMode] = React.useState(false);
    const [printConfig, setPrintConfig] = React.useState({
        title: 'Academic Attendance Report',
        logoUrl: '',
        headerText: 'School Year 2026-2027 | Attendance Documentation',
        footerText: 'This report serves as an official academic record generated by the Class Attendance Management System.',
        showSchedule: true
    });

    const generateReport = () => {
      const students = getStudents(classData.id);
      const records = getAttendanceRecords(classData.id);
      
      let filename = '';
      let csvContent = '';

      if (reportType === 'daily') {
        const filteredRecords = records.filter(r => r.date === selectedDate);
        filename = `${classData.name}_Daily_${selectedDate}.csv`;
        csvContent = generateDailyReport(students, filteredRecords);
      } else if (reportType === 'weekly') {
        const filteredRecords = records.filter(record => {
          const recordDate = record.date;
          return recordDate >= selectedWeek.start && recordDate <= selectedWeek.end;
        });
        filename = `${classData.name}_Weekly_${selectedWeek.start}_to_${selectedWeek.end}.csv`;
        csvContent = generateWeeklyReport(students, filteredRecords);
      } else if (reportType === 'monthly') {
        const year = parseInt(selectedMonth.split('-')[0]);
        const month = parseInt(selectedMonth.split('-')[1]);
        
        const filteredRecords = records.filter(record => {
          const recordDate = new Date(record.date);
          return recordDate.getFullYear() === year && recordDate.getMonth() + 1 === month;
        });
        filename = `${classData.name}_Monthly_${selectedMonth}.csv`;
        csvContent = generateMonthlyReport(students, filteredRecords, selectedMonth);
      } else if (reportType === 'period') {
        const days = parseInt(dateRange);
        const endDate = new Date();
        const startDate = new Date();
        startDate.setDate(endDate.getDate() - days);
        
        const filteredRecords = records.filter(record => {
          const recordDate = new Date(record.date);
          return recordDate >= startDate && recordDate <= endDate;
        });
        filename = `${classData.name}_Period_${days}days.csv`;
        csvContent = generatePeriodReport(students, filteredRecords);
      } else if (reportType === 'daily_summary') {
        filename = `${classData.name}_Daily_Summary.csv`;
        csvContent = generateDailySummaryReport(students, records);
      } else {
        filename = `${classData.name}_Summary.csv`;
        csvContent = generateSummaryReport(students, records);
      }

      downloadCSV(csvContent, filename);
    };

    const generateDailyReport = (students, records) => {
      let csv = 'Student Name,Student ID,Date,Day of Week,Session,Status,Check-in Time\n';
      const dayOfWeek = new Date(selectedDate).toLocaleDateString('en-US', { weekday: 'long' });
      students.forEach(student => {
        const record = records.find(r => r.studentId === student.studentId);
        const status = record ? record.status : 'Not Marked';
        const session = record ? (record.session || 'AM') : '-';
        const timestamp = record ? new Date(record.timestamp).toLocaleTimeString() : '-';
        csv += `"${student.name}","${student.studentId}","${new Date(selectedDate).toLocaleDateString()}","${dayOfWeek}","${session}","${status}","${timestamp}"\n`;
      });
      return csv;
    };

    const generateWeeklyReport = (students, records) => {
      const dates = [...new Set(records.map(r => r.date))].sort();
      let csv = 'Student Name,Student ID,Date,Day of Week,Status,Session\n';
      students.forEach(student => {
        dates.forEach(date => {
          const record = records.find(r => r.studentId === student.studentId && r.date === date);
          const status = record ? record.status : 'Not Marked';
          const session = record ? record.session || 'AM' : '-';
          const dayOfWeek = new Date(date).toLocaleDateString('en-US', { weekday: 'long' });
          csv += `"${student.name}","${student.studentId}","${new Date(date).toLocaleDateString()}","${dayOfWeek}","${status}","${session}"\n`;
        });
      });
      return csv;
    };

    const generateMonthlyReport = (students, records, monthYear) => {
      const dates = [...new Set(records.map(r => r.date))].sort();
      let csv = 'Student Name,Student ID,Date,Status,Session\n';
      students.forEach(student => {
        dates.forEach(date => {
          const record = records.find(r => r.studentId === student.studentId && r.date === date);
          const status = record ? record.status : 'Not Marked';
          const session = record ? record.session || 'AM' : '-';
          csv += `"${student.name}","${student.studentId}","${new Date(date).toLocaleDateString()}","${status}","${session}"\n`;
        });
      });
      return csv;
    };

    const generatePeriodReport = (students, records) => {
      const dates = [...new Set(records.map(r => r.date))].sort();
      let csv = 'Student Name,Student ID,Date,Status,Session\n';
      students.forEach(student => {
        dates.forEach(date => {
          const record = records.find(r => r.studentId === student.studentId && r.date === date);
          const status = record ? record.status : 'Not Marked';
          const session = record ? record.session || 'AM' : '-';
          csv += `"${student.name}","${student.studentId}","${new Date(date).toLocaleDateString()}","${status}","${session}"\n`;
        });
      });
      return csv;
    };

    const generateDailySummaryReport = (students, records) => {
      const dates = [...new Set(records.map(r => r.date))].sort();
      let csv = 'Date,Day of Week,Total Students,Present,Late,Absent\n';
      dates.forEach(date => {
        const dayRecords = records.filter(r => r.date === date);
        const present = dayRecords.filter(r => r.status === 'present').length;
        const late = dayRecords.filter(r => r.status === 'late').length;
        const absent = dayRecords.filter(r => r.status === 'absent').length;
        const dayOfWeek = new Date(date).toLocaleDateString('en-US', { weekday: 'long' });
        csv += `"${new Date(date).toLocaleDateString()}","${dayOfWeek}","${students.length}","${present}","${late}","${absent}"\n`;
      });
      return csv;
    };

    const generateSummaryReport = (students, records) => {
      const dates = [...new Set(records.map(r => r.date))].sort();
      let csv = 'Student Name,Student ID';
      dates.forEach(date => {
        csv += `,${new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`;
      });
      csv += ',Total Present,Total Late,Total Absent,Attendance %\n';
      students.forEach(student => {
        const studentRecords = records.filter(r => r.studentId === student.studentId);
        let p = 0, l = 0, a = 0;
        csv += `"${student.name}","${student.studentId}"`;
        dates.forEach(date => {
          const r = studentRecords.find(rec => rec.date === date);
          let s = '-';
          if (r) {
            if (r.status === 'present') { s = 'P'; p++; }
            else if (r.status === 'late') { s = 'L'; l++; }
            else if (r.status === 'absent') { s = 'A'; a++; }
          }
          csv += `,${s}`;
        });
        const rate = (p + l + a) > 0 ? Math.round((p / (p + l + a)) * 100) : 0;
        csv += `,${p},${l},${a},${rate}%\n`;
      });
      return csv;
    };

    const downloadCSV = (csvContent, filename) => {
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      if (link.download !== undefined) {
        const url = URL.createObjectURL(blob);
        link.setAttribute('href', url);
        link.setAttribute('download', filename);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      }
    };

    const handlePrint = () => {
        setIsPrintMode(true);
        setTimeout(() => {
            window.print();
            setIsPrintMode(false);
        }, 500);
    };

    if (isPrintMode) {
        const students = getStudents(classData.id);
        const records = getAttendanceRecords(classData.id);
        const dates = [...new Set(records.map(r => r.date))].sort().reverse().slice(0, 15);

        return (
            <div className="fixed inset-0 bg-slate-900 bg-opacity-95 z-[200] flex flex-col items-center overflow-auto p-4 md:p-10 no-print-overlay">
                <style>
                    {`
                    @media print {
                        .no-print-overlay { position: static; background: white; padding: 0; display: block; overflow: visible; }
                        .no-print { display: none !important; }
                        #printable-report { box-shadow: none !important; margin: 0 !important; width: 100% !important; padding: 0 !important; }
                    }
                    #printable-report table { border-collapse: collapse; width: 100%; }
                    #printable-report th, #printable-report td { border: 1px solid #000; padding: 4px; text-align: left; font-size: 10px; }
                    #printable-report .header-section { border-bottom: 2px solid #000; margin-bottom: 15px; padding-bottom: 10px; }
                    `}
                </style>
                
                {/* PDF Controls Overlay */}
                <div className="w-full max-w-4xl bg-white rounded-xl shadow-2xl p-6 mb-8 no-print border-t-4 border-blue-600">
                    <div className="flex items-center justify-between mb-6">
                        <h2 className="text-xl font-bold flex items-center gap-2">
                            <div className="icon-printer text-blue-600"></div>
                            Interactive PDF Report Builder
                        </h2>
                        <div className="flex gap-3">
                            <button onClick={() => setIsPrintMode(false)} className="btn btn-secondary py-2">
                                Close Builder
                            </button>
                            <button onClick={() => window.print()} className="btn btn-primary py-2 px-6 flex items-center gap-2">
                                <div className="icon-download"></div>
                                Download / Print PDF
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                        <div className="space-y-4">
                            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest">Header Layout</h3>
                            <div>
                                <label className="block text-xs font-bold mb-1">Report Title</label>
                                <input type="text" value={printConfig.title} onChange={e => setPrintConfig({...printConfig, title: e.target.value})} className="input-field py-1 text-sm"/>
                            </div>
                            <div>
                                <label className="block text-xs font-bold mb-1">Logo URL</label>
                                <input type="text" value={printConfig.logoUrl} onChange={e => setPrintConfig({...printConfig, logoUrl: e.target.value})} className="input-field py-1 text-sm" placeholder="https://..."/>
                            </div>
                        </div>
                        <div className="space-y-4">
                            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest">Sub-Text</h3>
                            <div>
                                <label className="block text-xs font-bold mb-1">Academic Department</label>
                                <input type="text" value={printConfig.headerText} onChange={e => setPrintConfig({...printConfig, headerText: e.target.value})} className="input-field py-1 text-sm"/>
                            </div>
                            <div>
                                <label className="block text-xs font-bold mb-1">Instructor Name</label>
                                <input type="text" defaultValue={classData.teacherEmail} className="input-field py-1 text-sm italic" readOnly/>
                            </div>
                        </div>
                        <div className="space-y-4">
                            <h3 className="text-sm font-black text-slate-400 uppercase tracking-widest">Page Settings</h3>
                            <div className="flex items-center gap-3 py-2">
                                <input type="checkbox" id="show-sched-pdf" checked={printConfig.showSchedule} onChange={e => setPrintConfig({...printConfig, showSchedule: e.target.checked})}/>
                                <label htmlFor="show-sched-pdf" className="text-xs font-bold">Show Class Schedule</label>
                            </div>
                            <div>
                                <label className="block text-xs font-bold mb-1">Footer Disclaimer</label>
                                <textarea value={printConfig.footerText} onChange={e => setPrintConfig({...printConfig, footerText: e.target.value})} className="input-field py-1 text-xs" rows="2"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                {/* The Paper Preview */}
                <div className="bg-white w-full max-w-[210mm] min-h-[297mm] p-[15mm] shadow-2xl text-black font-serif" id="printable-report">
                    <div className="header-section flex items-center justify-between">
                        {printConfig.logoUrl && <img src={printConfig.logoUrl} alt="Logo" className="h-16 w-16 object-contain" />}
                        <div className="text-center flex-1">
                            <h1 className="text-xl font-bold uppercase tracking-tight">{printConfig.title}</h1>
                            <p className="text-xs italic text-gray-600">{printConfig.headerText}</p>
                            <div className="mt-3 grid grid-cols-3 text-[10px] font-bold border-t border-black pt-2">
                                <p>CLASS: {classData.name}</p>
                                <p>SUBJECT: {classData.subject}</p>
                                <p>SY: {classData.schoolYear}</p>
                            </div>
                            {printConfig.showSchedule && (
                                <p className="text-[9px] text-gray-500 mt-1">
                                    SCHEDULE: {classData.days?.join(', ')} | {classData.startTime}-{classData.endTime}
                                </p>
                            )}
                        </div>
                    </div>

                    <div className="mt-4">
                        <h2 className="text-xs font-bold mb-2 border-b border-dashed border-gray-300 pb-1">ATTENDANCE LOG (RECENT 15 SESSIONS)</h2>
                        <table>
                            <thead>
                                <tr className="bg-slate-100">
                                    <th className="w-6 text-center">#</th>
                                    <th>STUDENT NAME</th>
                                    <th className="w-20">STUDENT ID</th>
                                    {dates.map(date => (
                                        <th key={date} className="text-center w-8">
                                            {new Date(date).toLocaleDateString(undefined, { month: '2-digit', day: '2-digit' })}
                                        </th>
                                    ))}
                                    <th className="text-center w-10">RATE</th>
                                </tr>
                            </thead>
                            <tbody>
                                {students.map((student, idx) => {
                                    const studentRecords = records.filter(r => r.studentId === student.studentId);
                                    const presentCount = studentRecords.filter(r => r.status === 'present').length;
                                    const rate = studentRecords.length > 0 ? Math.round((presentCount / studentRecords.length) * 100) : 0;
                                    return (
                                        <tr key={student.id}>
                                            <td className="text-center">{idx + 1}</td>
                                            <td className="font-bold">{student.name}</td>
                                            <td className="font-mono">{student.studentId}</td>
                                            {dates.map(date => {
                                                const r = records.find(rec => rec.studentId === student.studentId && rec.date === date);
                                                return (
                                                    <td key={date} className="text-center font-bold">
                                                        {r ? (r.status === 'present' ? 'P' : r.status === 'late' ? 'L' : 'A') : '-'}
                                                    </td>
                                                );
                                            })}
                                            <td className="text-center font-black">{rate}%</td>
                                        </tr>
                                    );
                                })}
                            </tbody>
                        </table>
                    </div>

                    <div className="mt-12 grid grid-cols-2 gap-16">
                        <div className="text-center">
                            <div className="border-b border-black h-8 w-full mb-1"></div>
                            <p className="text-[9px] font-bold uppercase">Authorized Instructor Signature</p>
                        </div>
                        <div className="text-center">
                            <div className="border-b border-black h-8 w-full mb-1 flex items-center justify-center font-serif text-sm">
                                {new Date().toLocaleDateString()}
                            </div>
                            <p className="text-[9px] font-bold uppercase">Date of Report Generation</p>
                        </div>
                    </div>

                    <div className="mt-auto pt-10 text-center">
                        <p className="text-[8px] text-gray-400 italic leading-tight">
                            {printConfig.footerText}
                        </p>
                        <p className="text-[7px] text-gray-300 mt-2 uppercase tracking-widest">
                            Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    return (
      <div className="space-y-6" data-name="report-generator" data-file="components/ReportGenerator.js">
        <div className="card">
          <h3 className="text-lg font-semibold text-[var(--text-primary)] mb-4">Export & Documentation</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div>
              <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
                Report Type
              </label>
              <select
                value={reportType}
                onChange={(e) => setReportType(e.target.value)}
                className="input-field"
              >
                <option value="summary">Consolidated Summary</option>
                <option value="daily">Detailed Daily Report</option>
                <option value="weekly">Weekly Report</option>
                <option value="monthly">Detailed Monthly Report</option>
                <option value="period">Period Report</option>
                <option value="daily_summary">Daily Summary Report</option>
              </select>
            </div>

            {reportType === 'daily' && (
              <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
                  Select Date
                </label>
                <input
                  type="date"
                  value={selectedDate}
                  onChange={(e) => setSelectedDate(e.target.value)}
                  className="input-field"
                />
              </div>
            )}

            {reportType === 'weekly' && (
              <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
                  Select Week
                </label>
                <input
                  type="week"
                  value={`${selectedWeek.start.slice(0, 4)}-W${Math.ceil((new Date(selectedWeek.start).getDate() + new Date(selectedWeek.start).getDay()) / 7)}`}
                  onChange={(e) => {
                    const weekStart = new Date(e.target.value);
                    setSelectedWeek(getWeekRange(weekStart));
                  }}
                  className="input-field"
                />
              </div>
            )}

            {reportType === 'monthly' && (
              <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
                  Select Month
                </label>
                <input
                  type="month"
                  value={selectedMonth}
                  onChange={(e) => setSelectedMonth(e.target.value)}
                  className="input-field"
                />
              </div>
            )}

            {reportType === 'period' && (
              <div>
                <label className="block text-sm font-medium text-[var(--text-primary)] mb-2">
                  Date Range
                </label>
                <select
                  value={dateRange}
                  onChange={(e) => setDateRange(e.target.value)}
                  className="input-field"
                >
                  <option value="7">Last 7 days</option>
                  <option value="14">Last 14 days</option>
                  <option value="30">Last 30 days</option>
                  <option value="60">Last 60 days</option>
                  <option value="90">Last 90 days</option>
                </select>
              </div>
            )}

            <div className="flex items-end gap-2">
              <button onClick={generateReport} className="btn btn-secondary flex-1" title="Download Excel-compatible CSV">
                CSV Export
              </button>
              <button onClick={handlePrint} className="btn btn-primary flex-1 flex items-center justify-center gap-2">
                <div className="icon-printer text-lg"></div>
                Print / PDF
              </button>
            </div>
          </div>

          <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 space-y-4">
            <div className="flex items-center gap-2 text-slate-800 mb-2">
                <div className="icon-settings text-xl"></div>
                <h4 className="font-bold">PDF Report Header Configuration</h4>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label className="block text-xs font-bold uppercase text-slate-500 mb-1">Main Report Title</label>
                    <input 
                        type="text" 
                        value={printConfig.title} 
                        onChange={e => setPrintConfig({...printConfig, title: e.target.value})}
                        className="input-field py-2"
                        placeholder="e.g. Official Class Record"
                    />
                </div>
                <div>
                    <label className="block text-xs font-bold uppercase text-slate-500 mb-1">Logo URL (Optional)</label>
                    <input 
                        type="text" 
                        value={printConfig.logoUrl} 
                        onChange={e => setPrintConfig({...printConfig, logoUrl: e.target.value})}
                        className="input-field py-2"
                        placeholder="https://..."
                    />
                </div>
                <div className="md:col-span-2">
                    <label className="block text-xs font-bold uppercase text-slate-500 mb-1">Header Subtext / Department</label>
                    <input 
                        type="text" 
                        value={printConfig.headerText} 
                        onChange={e => setPrintConfig({...printConfig, headerText: e.target.value})}
                        className="input-field py-2"
                        placeholder="e.g. Department of Engineering | 1st Semester"
                    />
                </div>
                <div className="md:col-span-2">
                    <label className="block text-xs font-bold uppercase text-slate-500 mb-1">Footer Legal/Notice Text</label>
                    <textarea 
                        value={printConfig.footerText} 
                        onChange={e => setPrintConfig({...printConfig, footerText: e.target.value})}
                        className="input-field py-2"
                        rows="2"
                    />
                </div>
                <div className="flex items-center gap-2">
                    <input 
                        type="checkbox" 
                        id="show-schedule-print"
                        checked={printConfig.showSchedule}
                        onChange={e => setPrintConfig({...printConfig, showSchedule: e.target.checked})}
                    />
                    <label htmlFor="show-schedule-print" className="text-sm font-medium text-slate-700">Include Class Schedule in Header</label>
                </div>
            </div>
          </div>

          {showScheduleForm && (
            <ClassScheduleForm 
              classData={classData}
              onSave={() => setShowScheduleForm(false)}
              onCancel={() => setShowScheduleForm(false)}
            />
          )}
        </div>
      </div>
    );
  } catch (error) {
    console.error('ReportGenerator component error:', error);
    return null;
  }
}